### Register User API
POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Dwi Armandhani",
    "email" : "dwiar55.arman@gmail.com",
    "password": "@aduhlupa123",
}